payment_method.settings.stripe:
  mapping:
    testmode:
      type: boolean
    test_publishable_key:
      type: string
    live_publishable_key:
      type: string
    test_secret_key:
      type: string
    live_secret_key:
      type: string
